### PR TITLE
Removed ambiguity in readme

### PR DESCRIPTION
**Pull request by JMarple**
I made a few changes to the readme:
- Removed a few passive aggressive remarks that didn't belong in the readme.  
- Removed ambiguity in the coding style.  I tried following the Google C++ style guide for the added remarks.  I'd be willing to discuss changes to the coding style if others disagree with it.

### CODE REVIEW

**Comment by EvolvedAwesome** [comment]
I would suggest using spaces above tabs (keeping in line with what Pixel originally had). Github screws with tabs and makes them 8 spaces of length (at least, in some cases it would seem). Using spaces instead of tabs retains the formatting of your file in github. (Please do correct me if im wrong here, I haven't been active on github in a while).

Importantly, you can convert to spaces in RobotC easily by navigating to "edit->code formatting->Untabify Selection/Untabify Whole File", so it's not an ungodly process involving external editors and the likes.

And while you're at it, you should probably put something around comment format. Firstly whether you should use inline or side comments to describe something happening in the code. You should probably mention that you should split up your comments into multiple lines for ease of reading instead of having to reach that 100char limit every comment line.

**Comment by JMarple** [comment]
I'd be willing to use spaces instead of tabs if that's the consensus.  My only worry is that there will be a lot of commits with tabs since that's the default in the robotc editor.  

I believe inline comments should be used exclusively.  I agree with the splitting up the multiple lines.  On personal projects I usually keep comments to around 60 characters and everything else 80 characters but I know a lot of people don't like this restriction.  What is the consensus on this?

**Comment by BottomNotch** [comment]
80 character limit is pretty standard, I'm rather annoyed when it's not followed.

As for tabs, "tabs are evil, bad bad tabs" -The Doctor.  If someone commits something with tabs and it ends up being problematic just make a pull request to untabify.

**Comment by pingbird** [comment]
Wew thanks, i diddn't realize i was that bad at english

so for syntax

```
while (x == y)
{
```

vs

```
while (x == y) {
```

most of us (AFAIK) use the latter in real C/C++ so its pretty hard to force everyone

I agree we should have a limit on comment line length

**Pull request merged**
